CREATE TABLE IF NOT EXISTS roles (
ID SERIAL PRIMARY KEY,
Name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
ID VARCHAR(20) PRIMARY KEY,
L_Name VARCHAR(40) NOT NULL,
F_Name VARCHAR(40) NOT NULL,
Role_ID INT NOT NULL DEFAULT 1 REFERENCES roles(ID) ON DELETE SET DEFAULT
);

CREATE TABLE IF NOT EXISTS permissions (
ID SERIAL PRIMARY KEY,
Name VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS role_permission (
Role_ID INT NOT NULL REFERENCES roles(ID) ON DELETE CASCADE,
Permission_ID INT NOT NULL REFERENCES permissions(ID) ON DELETE CASCADE,
PRIMARY KEY (Role_ID, Permission_ID)
);

CREATE TABLE IF NOT EXISTS "groups" (
ID SERIAL PRIMARY KEY,
Name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_roup (
User_ID VARCHAR NOT NULL REFERENCES users(ID) ON DELETE CASCADE,
Group_ID INT NOT NULL REFERENCES "groups"(ID) ON DELETE CASCADE,
PRIMARY KEY (User_ID, Group_ID)
);

CREATE TABLE IF NOT EXISTS softskills (
ID SERIAL PRIMARY KEY,
Name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS behaviors (
ID SERIAL PRIMARY KEY,
Name VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS behavior_skill (
Behavior_ID INT NOT NULL REFERENCES behaviors(ID) ON DELETE CASCADE,
Softskill_ID INT NOT NULL REFERENCES softskills(ID) ON DELETE CASCADE,
PRIMARY KEY(Behavior_ID, Softskill_ID)
);

CREATE TABLE IF NOT EXISTS behavior_sets (
ID SERIAL PRIMARY KEY,
Name VARCHAR (40) NOT NULL
);

CREATE TABLE IF NOT EXISTS behavior_to_set (
Behavior_ID INT NOT NULL REFERENCES behaviors(ID) ON DELETE CASCADE,
Set_ID INT NOT NULL REFERENCES behavior_sets(ID) ON DELETE CASCADE,
PRIMARY KEY (Behavior_ID, Set_ID)
);

CREATE TABLE IF NOT EXISTS records (
ID BIGSERIAL PRIMARY KEY,
Title VARCHAR(40) NOT NULL,
Receiver_ID VARCHAR NOT NULL REFERENCES users(ID) ON DELETE CASCADE,
Creator_ID VARCHAR REFERENCES users(ID) ON DELETE SET NULL,
Behavior_ID INT NOT NULL REFERENCES behaviors(ID) ON DELETE CASCADE,
Comment TEXT,
Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);