CREATE TABLE IF NOT EXISTS roles (
ID SERIAL PRIMARY KEY,
Name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
ID VARCHAR(20) PRIMARY KEY,
LName VARCHAR(40) NOT NULL,
FName VARCHAR(40) NOT NULL,
RoleID INT NOT NULL DEFAULT 1 REFERENCES roles(ID) ON DELETE SET DEFAULT
);

CREATE TABLE IF NOT EXISTS permissions (
ID SERIAL PRIMARY KEY,
Name VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS rolePermission (
RoleID INT NOT NULL REFERENCES roles(ID) ON DELETE CASCADE,
PermissionID INT NOT NULL REFERENCES permissions(ID) ON DELETE CASCADE,
PRIMARY KEY (RoleID, PermissionID)
);

CREATE TABLE IF NOT EXISTS 'groups' (
ID SERIAL PRIMARY KEY,
Name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS userGroup (
UserID VARCHAR NOT NULL REFERENCES users(ID) ON DELETE CASCADE,
GroupID INT NOT NULL REFERENCES 'groups'(ID) ON DELETE CASCADE,
PRIMARY KEY (UserID, GroupID)
);

CREATE TABLE IF NOT EXISTS softskills (
ID SERIAL PRIMARY KEY,
Name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS behaviors (
ID SERIAL PRIMARY KEY,
Name VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS behaviorSkill (
BehaviorID INT NOT NULL REFERENCES behaviors(ID) ON DELETE CASCADE,
SoftskillID INT NOT NULL REFERENCES softskills(ID) ON DELETE CASCADE,
PRIMARY KEY(BehaviorID, SoftskillID)
);

CREATE TABLE IF NOT EXISTS behaviorSets (
ID SERIAL PRIMARY KEY,
Name VARCHAR (40) NOT NULL
);

CREATE TABLE IF NOT EXISTS behaviorToSet (
BehaviorID INT NOT NULL REFERENCES behaviors(ID) ON DELETE CASCADE,
SetID INT NOT NULL REFERENCES behaviorSets(ID) ON DELETE CASCADE,
PRIMARY KEY (BehaviorID, SetID)
);

CREATE TABLE IF NOT EXISTS records (
ID BIGSERIAL PRIMARY KEY,
Title VARCHAR(40) NOT NULL,
ReceiverID VARCHAR NOT NULL REFERENCES users(ID) ON DELETE CASCADE,
CreatorID VARCHAR REFERENCES users(ID) ON DELETE SET NULL,
BehaviorID INT NOT NULL REFERENCES behaviors(ID) ON DELETE CASCADE,
Comment TEXT,
CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);