openapi: 3.1.1
info:
  title: SoftTrack API
  version: 0.1.0

servers:
  - url: http://localhost:8080
    description: For local development only

paths:
  /session:
    post:
      summary: Log into user account
      tags:
        - session

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionCreate'

      responses:
        '201':
          description: Success. JWT saved in the `session` cookie.
        '401':
          description: Invalid username or password

    get:
      summary: Get current authorized user
      tags:
        - session

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
        '401':
          description: Unauthorized
    
    delete:
      summary: Log out of user account
      description: Deletes the `session` cookie
      tags:
        - session

      responses:
        '200':
          description: Cookie deleted successfully

components:
  schemas:
    Session:
      type: object
      properties:
        id:
          type: number
        username:
          type: string

    SessionCreate:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
